### ISSUE TITLE
Some mutations might be double counted

### ISSUE THREAD

**Issue by ynshen** [ncharest/Ribozyme-Sequence-Optimization#1]
Hi Nate,

When I was reading the code for this part: 
https://github.com/ncharest/Ribozyme-Sequence-Optimization/blob/651a3d2c1df14e0bd93e7c4a1794a46e4b9b39a1/rna_analysis.py#L298-L306

I feel some mutants might be double-counted when you are moving to the next layer (mutations back to the inner layer). I vaguely remembered you mentioned you have fixed this in one meeting - just to double-check.

**Comment by ncharest** [comment]
Yuning,

The double counting was intentionally kept due to the fact we view the
space as a graph with directed edges. Since an M#N mutation is physically
distinct from an N#M mutation (and the delKa the inverse) I allowed the
code to compute and represent both edges so that the ensemble of edges most
closely resembled my inner picture of the physical situation. In my
understanding, allowing the symmetry was more 'honest' than artificially
removing it, as that would embed a notion of "spreading out" from the seed
node that I didn't necessarily want to include in the statistics.

I admit this was a thinker for me, though, so if you can think of a reason
for allowing the asymmetry I am definitely open to discussing it!

Incidentally that code is a little depreciated. I haven't been very prompt
in keeping it up to date. I'm attaching the most recent file here.

Cheers,
-Nate
